# Generated by Django 6.0.6 on 2026-08-16 15:18

import apps.products.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Fragrance Note',
                'verbose_name_plural': 'Fragrance Notes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('concentration', models.CharField(choices=[('unspecified', 'Unspecified'), ('extrait_de_parfum', 'Extrait de Parfum'), ('parfum', 'Parfum'), ('eau_de_parfum', 'Eau de Parfum'), ('eau_de_toilette', 'Eau de Toilette'), ('eau_de_cologne', 'Eau de Cologne')], default='unspecified', max_length=32)),
                ('volume_ml', models.PositiveIntegerField(help_text='Package volume in millilitres.', validators=[django.core.validators.MinValueValidator(1)])),
                ('country_of_origin', models.CharField(blank=True, help_text='Country where the product was made.', max_length=100)),
                ('target_audience', models.CharField(choices=[('unspecified', 'Unspecified'), ('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unspecified', max_length=16)),
                ('fragrance_family', models.CharField(choices=[('unspecified', 'Unspecified'), ('amber', 'Amber'), ('aromatic', 'Aromatic'), ('aquatic', 'Aquatic'), ('chypre', 'Chypre'), ('citrus', 'Citrus'), ('floral', 'Floral'), ('fougere', 'Fougere'), ('fruity', 'Fruity'), ('gourmand', 'Gourmand'), ('green', 'Green'), ('leather', 'Leather'), ('musk', 'Musk'), ('powdery', 'Powdery'), ('spicy', 'Spicy'), ('woody', 'Woody'), ('other', 'Other')], default='unspecified', help_text='Primary fragrance family or main accord.', max_length=16)),
                ('introduction_year', models.PositiveSmallIntegerField(blank=True, help_text='Year the fragrance was introduced.', null=True, validators=[django.core.validators.MinValueValidator(1700), apps.products.models.validate_introduction_year])),
                ('suitable_season', models.CharField(choices=[('unspecified', 'Unspecified'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all_seasons', 'All seasons')], default='unspecified', max_length=16)),
                ('suitable_usage_time', models.CharField(choices=[('unspecified', 'Unspecified'), ('day', 'Day'), ('night', 'Night'), ('day_and_night', 'Day and night')], default='unspecified', max_length=16)),
                ('barcode', models.CharField(blank=True, help_text='Optional 8-14 digit retail barcode; distinct from the SKU.', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must contain between 8 and 14 digits.', regex='^[0-9]{8,14}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFragranceNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('base', 'Base')], max_length=6)),
                ('position', models.PositiveIntegerField(help_text='1-based order within this product and layer.', validators=[django.core.validators.MinValueValidator(1)])),
                ('fragrance_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.fragrancenote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_note_links', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Fragrance Note',
                'verbose_name_plural': 'Product Fragrance Notes',
                'ordering': ['layer', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_notes',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductFragranceNote', to='products.fragrancenote'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='products/thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productfragrancenote',
            constraint=models.UniqueConstraint(fields=('product', 'layer', 'fragrance_note'), name='unique_product_note_per_layer'),
        ),
        migrations.AddConstraint(
            model_name='productfragrancenote',
            constraint=models.UniqueConstraint(fields=('product', 'layer', 'position'), name='unique_product_note_position'),
        ),
        migrations.AddConstraint(
            model_name='productfragrancenote',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='product_note_position_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='productfragrancenote',
            constraint=models.CheckConstraint(condition=models.Q(('layer__in', ('top', 'middle', 'base'))), name='product_note_valid_layer'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), ('discount_price__lt', models.F('price')), _connector='OR'), name='product_discount_lower_than_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('volume_ml__gte', 1)), name='product_positive_volume_ml'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('introduction_year__isnull', True), ('introduction_year__gte', 1700), _connector='OR'), name='product_introduction_year_not_before_1700'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_image_per_product'),
        ),
    ]
