# Generated by Django 6.0.6 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="products/thumbnails/"),
        ),
    ]
