# Generated by Django 6.0.6 on 2026-08-11 15:53

import apps.products.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Fragrance Note',
                'verbose_name_plural': 'Fragrance Notes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='abv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ibu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serving_temp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='taste_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vintage_year',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Optional 8-14 digit retail barcode; distinct from the SKU.', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must contain between 8 and 14 digits.', regex='^[0-9]{8,14}$')]),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('extrait_de_parfum', 'Extrait de Parfum'), ('parfum', 'Parfum'), ('eau_de_parfum', 'Eau de Parfum'), ('eau_de_toilette', 'Eau de Toilette'), ('eau_de_cologne', 'Eau de Cologne'), ('body_splash', 'Body Splash')], default='unspecified', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_family',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('amber', 'Amber'), ('aromatic', 'Aromatic'), ('aquatic', 'Aquatic'), ('chypre', 'Chypre'), ('citrus', 'Citrus'), ('floral', 'Floral'), ('fougere', 'Fougere'), ('fruity', 'Fruity'), ('gourmand', 'Gourmand'), ('green', 'Green'), ('leather', 'Leather'), ('musk', 'Musk'), ('powdery', 'Powdery'), ('spicy', 'Spicy'), ('woody', 'Woody'), ('other', 'Other')], default='unspecified', help_text='Primary fragrance family or main accord.', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='introduction_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the fragrance was introduced.', null=True, validators=[django.core.validators.MinValueValidator(1700), apps.products.models.validate_introduction_year]),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_season',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all_seasons', 'All seasons')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_usage_time',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('day', 'Day'), ('night', 'Night'), ('day_and_night', 'Day and night')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unspecified', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='Country where the product was made.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(help_text='Package volume in millilitres.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.ManyToManyField(blank=True, related_name='base_note_products', to='products.fragrancenote'),
        ),
        migrations.AddField(
            model_name='product',
            name='middle_notes',
            field=models.ManyToManyField(blank=True, related_name='middle_note_products', to='products.fragrancenote'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.ManyToManyField(blank=True, related_name='top_note_products', to='products.fragrancenote'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('volume_ml__gte', 1)), name='product_positive_volume_ml'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('introduction_year__isnull', True), ('introduction_year__gte', 1700), _connector='OR'), name='product_introduction_year_not_before_1700'),
        ),
    ]
