# Generated by Django 6.0.6 on 2026-08-11 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


LEGACY_NOTE_LAYERS = (
    ("top_notes", "top"),
    ("middle_notes", "middle"),
    ("base_notes", "base"),
)


def copy_legacy_fragrance_notes(apps, schema_editor):
    """Preserve the old API's name-ordered note membership as explicit positions."""
    Product = apps.get_model("products", "Product")
    ProductFragranceNote = apps.get_model("products", "ProductFragranceNote")
    database = schema_editor.connection.alias
    pending = []

    for field_name, layer in LEGACY_NOTE_LAYERS:
        legacy_through = Product._meta.get_field(field_name).remote_field.through
        legacy_links = (
            legacy_through.objects.using(database)
            .order_by("product_id", "fragrancenote__name", "fragrancenote_id")
            .values_list("product_id", "fragrancenote_id")
        )
        previous_product_id = None
        position = 0
        for product_id, note_id in legacy_links.iterator(chunk_size=1000):
            if product_id != previous_product_id:
                previous_product_id = product_id
                position = 1
            else:
                position += 1
            pending.append(
                ProductFragranceNote(
                    product_id=product_id,
                    fragrance_note_id=note_id,
                    layer=layer,
                    position=position,
                )
            )
            if len(pending) >= 1000:
                ProductFragranceNote.objects.using(database).bulk_create(pending)
                pending.clear()

    if pending:
        ProductFragranceNote.objects.using(database).bulk_create(pending)


def restore_legacy_fragrance_notes(apps, schema_editor):
    """Restore layer membership when rolling the schema back; order cannot survive."""
    Product = apps.get_model("products", "Product")
    ProductFragranceNote = apps.get_model("products", "ProductFragranceNote")
    database = schema_editor.connection.alias

    for field_name, layer in LEGACY_NOTE_LAYERS:
        legacy_through = Product._meta.get_field(field_name).remote_field.through
        pending = []
        links = (
            ProductFragranceNote.objects.using(database)
            .filter(layer=layer)
            .order_by("product_id", "position", "id")
            .values_list("product_id", "fragrance_note_id")
        )
        for product_id, note_id in links.iterator(chunk_size=1000):
            pending.append(
                legacy_through(
                    product_id=product_id,
                    fragrancenote_id=note_id,
                )
            )
            if len(pending) >= 1000:
                legacy_through.objects.using(database).bulk_create(pending)
                pending.clear()
        if pending:
            legacy_through.objects.using(database).bulk_create(pending)


def normalize_body_splash_concentration(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.using(schema_editor.connection.alias).filter(
        concentration="body_splash"
    ).update(concentration="unspecified")


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_fragrancenote_remove_product_abv_remove_product_ibu_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFragranceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("middle", "Middle"),
                            ("base", "Base"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="1-based order within this product and layer.",
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "fragrance_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="products.fragrancenote",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragrance_note_links",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Fragrance Note",
                "verbose_name_plural": "Product Fragrance Notes",
                "ordering": ["layer", "position", "id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="fragrance_notes",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="products.ProductFragranceNote",
                to="products.fragrancenote",
            ),
        ),
        migrations.RunPython(
            copy_legacy_fragrance_notes,
            restore_legacy_fragrance_notes,
        ),
        migrations.RemoveField(
            model_name="product",
            name="base_notes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="middle_notes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="top_notes",
        ),
        migrations.RunPython(
            normalize_body_splash_concentration,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="product",
            name="concentration",
            field=models.CharField(
                choices=[
                    ("unspecified", "Unspecified"),
                    ("extrait_de_parfum", "Extrait de Parfum"),
                    ("parfum", "Parfum"),
                    ("eau_de_parfum", "Eau de Parfum"),
                    ("eau_de_toilette", "Eau de Toilette"),
                    ("eau_de_cologne", "Eau de Cologne"),
                ],
                default="unspecified",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="productfragrancenote",
            constraint=models.UniqueConstraint(
                fields=("product", "layer", "fragrance_note"),
                name="unique_product_note_per_layer",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfragrancenote",
            constraint=models.UniqueConstraint(
                fields=("product", "layer", "position"),
                name="unique_product_note_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfragrancenote",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="product_note_position_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfragrancenote",
            constraint=models.CheckConstraint(
                condition=models.Q(("layer__in", ("top", "middle", "base"))),
                name="product_note_valid_layer",
            ),
        ),
    ]
