# Generated by Django 6.0.6 on 2026-08-27 21:50

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_address_uuid', models.UUIDField(editable=False, null=True)),
                ('idempotency_key', models.UUIDField()),
                ('status', models.CharField(choices=[('waiting_for_payment', 'Waiting for payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='waiting_for_payment', max_length=24)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('customer_first_name', models.CharField(blank=True, max_length=50)),
                ('customer_last_name', models.CharField(blank=True, max_length=50)),
                ('customer_phone_number', models.CharField(blank=True, max_length=11)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_title', models.CharField(max_length=50)),
                ('shipping_full_address', models.TextField()),
                ('shipping_postal_code', models.CharField(blank=True, max_length=10)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('payment_failed', 'Payment failed'), ('reservation_expired', 'Reservation expired')], max_length=32)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('late_payment_detected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_uuid', models.UUIDField(editable=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('released', 'Released')], default='active', max_length=12)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='orders.orderitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'waiting_for_payment')), fields=['reservation_expires_at', 'id'], name='orders_waiting_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='orders_user_idempotency_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting_for_payment')), fields=('user',), name='orders_one_waiting_per_user'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('waiting_for_payment', 'processing', 'shipped', 'delivered', 'cancelled'))), name='orders_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('shipping_amount__gte', 0), ('total__gte', 0)), name='orders_nonnegative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('shipping_amount')))), name='orders_total_matches_components'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation_expires_at__isnull', False), ('status', 'waiting_for_payment')), models.Q(('status', 'waiting_for_payment'), _negated=True), _connector='OR'), name='orders_waiting_has_deadline'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_expires_at__isnull', True), ('reservation_expires_at__gt', models.F('created_at')), _connector='OR'), name='orders_deadline_after_created'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'cancelled')), models.Q(('status', 'cancelled'), _negated=True), _connector='OR'), name='orders_cancelled_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('late_payment_detected_at__isnull', True), ('status', 'cancelled'), _connector='OR'), name='orders_late_payment_only_cancelled'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product_uuid'), name='orders_item_unique_product_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orders_item_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0), ('line_total__gte', 0)), name='orders_item_valid_amounts'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='orders_item_line_total_matches'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'consumed', 'released'))), name='orders_reservation_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_at__isnull', False), ('release_reason', ''), ('released_at__isnull', True), ('status', 'consumed')), models.Q(('status', 'consumed'), _negated=True), _connector='OR'), name='orders_reservation_consumed_fields'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_at__isnull', True), ('released_at__isnull', False), ('status', 'released')), models.Q(('status', 'released'), _negated=True), _connector='OR'), name='orders_reservation_released_fields'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_at__isnull', True), ('release_reason', ''), ('released_at__isnull', True), ('status', 'active')), models.Q(('status', 'active'), _negated=True), _connector='OR'), name='orders_reservation_active_fields'),
        ),
    ]
