services:
  web:
    command:
      - gunicorn
      - config.wsgi:application
      - --bind
      - 0.0.0.0:8000
      - --worker-class
      - gthread
      - --workers
      - "1"
      - --threads
      - "4"
      - --timeout
      - "60"
      - --keep-alive
      - "5"

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - type: bind
        source: /srv/wine-shop/staticfiles
        target: /app/staticfiles

      - type: bind
        source: /srv/wine-shop/media
        target: /app/media

  celery:
    command:
      - celery
      - -A
      - config
      - worker
      - --loglevel=INFO
      - --concurrency=1

    volumes:
      - type: bind
        source: /srv/wine-shop/media
        target: /app/media