[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test

# به پای‌تست می‌گوییم چه فایل‌هایی را به عنوان فایل تست شناسایی کند
python_files = tests.py test_*.py *_tests.py

# جلوگیری از نشان دادن هشدارهای منسوخ شدن پکیج‌های جانبی در ترمینال
addopts = --disable-warnings
