services:
  web:
    image: ${APP_IMAGE:?APP_IMAGE is required}
    command:
      - gunicorn
      - --config
      - docker/gunicorn.conf.py
      - --workers
      - "1"
      - --threads
      - "2"
      - config.wsgi:application

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - type: bind
        source: /srv/luxury-perfume/staticfiles
        target: /app/staticfiles

      - type: bind
        source: /srv/luxury-perfume/media
        target: /app/media

    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

  celery:
    image: ${APP_IMAGE:?APP_IMAGE is required}
    command:
      - celery
      - -A
      - config
      - worker
      - --loglevel=INFO
      - --concurrency=1

    volumes:
      - type: bind
        source: /srv/luxury-perfume/media
        target: /app/media

    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

  celery-beat:
    image: ${APP_IMAGE:?APP_IMAGE is required}
    command:
      - celery
      - -A
      - config
      - beat
      - --loglevel=INFO

    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

  db:
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
