# Generated by Django 6.0.6 on 2026-08-28 10:24

import django.core.validators
import decimal
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redirect_ready', 'Redirect ready'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Manual review')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('currency', models.CharField(default='IRT', editable=False, max_length=3)),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('captured_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('provider_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_receipt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('initiator_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('initiator_user_agent', models.CharField(blank=True, max_length=512)),
                ('initiator_request_id', models.CharField(max_length=32)),
                ('first_callback_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_callback_at', models.DateTimeField(blank=True, null=True)),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('callback_count', models.PositiveIntegerField(default=0)),
                ('provider_requested_at', models.DateTimeField(blank=True, null=True)),
                ('redirect_ready_at', models.DateTimeField(blank=True, null=True)),
                ('operation_token', models.UUIDField(blank=True, null=True)),
                ('operation_started_at', models.DateTimeField(blank=True, null=True)),
                ('provider_paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_at', models.DateTimeField(blank=True, null=True)),
                ('applied_to_order_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('reconciliation_attempts', models.PositiveIntegerField(default=0)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('next_reconciliation_at', models.DateTimeField(blank=True, null=True)),
                ('audit_scrubbed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('reason', models.CharField(choices=[('late_payment', 'Late payment'), ('duplicate_payment', 'Duplicate payment'), ('amount_mismatch', 'Amount mismatch')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('manual_review', 'Manual review')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('currency', models.CharField(default='IRT', editable=False, max_length=3)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_receipt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_token', models.UUIDField(blank=True, null=True)),
                ('operation_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payments_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('status__in', ('pending', 'redirect_ready', 'verifying', 'manual_review'))), fields=['next_reconciliation_at', 'id'], name='payments_reconcile_due_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('audit_scrubbed_at__isnull', True)), fields=['created_at', 'id'], name='payments_audit_unscrub_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('captured_amount__isnull', True), ('captured_amount__gt', 0), _connector='OR'), name='payments_capture_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IRT')), name='payments_payment_currency_irt'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('captured_currency__isnull', True), ('captured_currency__regex', '^[A-Z]{3}$'), _connector='OR'), name='payments_capture_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'redirect_ready', 'verifying', 'verified', 'failed', 'manual_review'))), name='payments_payment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_started_at__isnull', True), ('operation_token__isnull', True)), models.Q(('operation_started_at__isnull', False), ('operation_token__isnull', False)), _connector='OR'), name='payments_operation_fields_paired'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('redirect_ready', 'verifying', 'verified')), _negated=True), models.Q(('provider_session_id__isnull', False), ('redirect_ready_at__isnull', False)), _connector='OR'), name='payments_session_state_fields'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'verifying'), _negated=True), models.Q(('operation_started_at__isnull', False), ('operation_token__isnull', False)), _connector='OR'), name='payments_verifying_has_operation'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'verified'), _negated=True), models.Q(('captured_amount__gt', 0), ('captured_currency__regex', '^[A-Z]{3}$'), ('failed_at__isnull', True), ('manual_review_at__isnull', True), ('provider_session_id__isnull', False), ('provider_transaction_id__isnull', False), ('verified_at__isnull', False)), _connector='OR'), name='payments_verified_fields'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), models.Q(('failed_at__isnull', False), models.Q(('failure_code', ''), _negated=True), ('captured_amount__isnull', True), ('captured_currency__isnull', True), ('manual_review_at__isnull', True), ('verified_at__isnull', True)), _connector='OR'), name='payments_failed_fields'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'manual_review'), _negated=True), models.Q(('manual_review_at__isnull', False), models.Q(('failure_code', ''), _negated=True)), _connector='OR'), name='payments_review_fields'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('applied_to_order_at__isnull', True), ('status', 'verified'), _connector='OR'), name='payments_applied_only_verified'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('callback_count', 0), ('first_callback_at__isnull', True), ('last_callback_at__isnull', True)), models.Q(('callback_count__gt', 0), ('first_callback_at__isnull', False), ('last_callback_at__isnull', False)), _connector='OR'), name='payments_callback_fields'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_session_id__isnull', False)), fields=('provider', 'provider_session_id'), name='payments_provider_session_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id__isnull', False)), fields=('provider', 'provider_transaction_id'), name='payments_provider_transaction_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('applied_to_order_at__isnull', False)), fields=('order',), name='payments_one_applied_per_order'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'redirect_ready', 'verifying', 'manual_review'))), fields=('order',), name='payments_one_open_per_order'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='payments_refund_status_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(condition=models.Q(('status__in', ('pending', 'processing'))), fields=['next_retry_at', 'id'], name='payments_refund_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='payments_refund_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ('late_payment', 'duplicate_payment', 'amount_mismatch'))), name='payments_refund_valid_reason'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'refunded', 'manual_review'))), name='payments_refund_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_started_at__isnull', True), ('operation_token__isnull', True)), models.Q(('operation_started_at__isnull', False), ('operation_token__isnull', False)), _connector='OR'), name='payments_refund_operation_pair'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'processing'), _negated=True), models.Q(('operation_started_at__isnull', False), ('operation_token__isnull', False), ('processing_at__isnull', False)), _connector='OR'), name='payments_refund_processing'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'refunded'), _negated=True), models.Q(('refunded_at__isnull', False), models.Q(('provider_refund_id__isnull', False), ('completed_by__isnull', False), _connector='OR')), _connector='OR'), name='payments_refunded_evidence'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'manual_review'), _negated=True), models.Q(('manual_review_at__isnull', False), models.Q(('failure_code', ''), _negated=True)), _connector='OR'), name='payments_refund_review'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('payment',), name='payments_one_refund_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id__isnull', False)), fields=('provider', 'provider_refund_id'), name='payments_provider_refund_unique'),
        ),
    ]
