# Generated by Django 6.0.6 on 2026-07-31 14:49

from django.db import migrations, models


def deactivate_active_identityless_users(apps, schema_editor):
    """Make legacy rows conform before enforcing the active-user invariant."""
    CustomUser = apps.get_model("users", "CustomUser")
    for user in CustomUser.objects.filter(is_active=True).iterator():
        has_username = bool(user.username and user.username.strip())
        has_phone_number = bool(user.phone_number and user.phone_number.strip())
        if not has_username and not has_phone_number:
            user.is_active = False
            user.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RunPython(
            deactivate_active_identityless_users,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('username__isnull', False), models.Q(('username', ''), _negated=True)), models.Q(('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), _connector='OR'), name='users_active_user_requires_identity'),
        ),
    ]
