export const productsPage = {
  count: 3,
  total_pages: 1,
  current_page: 1,
  page_size: 20,
  links: { next: null, previous: null },
  results: [
    {
      uuid: "11111111-1111-4111-8111-111111111111",
      name: "Sauvage Elixir",
      slug: "sauvage-elixir",
      sku: "DIOR-SE-60",
      price: "7500000.00",
      discount_price: "6250000.00",
      final_price: "6250000.00",
      stock: 8,
      concentration: "parfum",
      target_audience: "men",
      fragrance_family: "aromatic",
      introduction_year: 2021,
      suitable_season: "winter",
      suitable_usage_time: "night",
      volume_ml: 60,
      category: { uuid: "dddddddd-dddd-4ddd-8ddd-dddddddddddd", name: "Perfume", slug: "perfume" },
      brand: {
        uuid: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
        name: "Dior",
        slug: "dior",
        country: "france",
      },
      primary_image: {
        id: 1,
        image: "http://localhost:8000/media/products/sauvage.jpg",
        thumbnail: "http://localhost:8000/media/products/sauvage-thumb.jpg",
        is_primary: true,
        display_order: 0,
      },
      is_featured: true,
      created_at: "2026-08-01T10:00:00Z",
    },
    {
      uuid: "22222222-2222-4222-8222-222222222222",
      name: "Naxos",
      slug: "naxos",
      sku: "XJ-NX-100",
      price: "8900000.00",
      discount_price: null,
      final_price: "8900000.00",
      stock: 4,
      concentration: "eau_de_parfum",
      target_audience: "unisex",
      fragrance_family: "amber",
      introduction_year: 2015,
      suitable_season: "autumn",
      suitable_usage_time: "night",
      volume_ml: 100,
      category: { uuid: "dddddddd-dddd-4ddd-8ddd-dddddddddddd", name: "Perfume", slug: "perfume" },
      brand: {
        uuid: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
        name: "Xerjoff",
        slug: "xerjoff",
        country: "italy",
      },
      primary_image: null,
      is_featured: false,
      created_at: "2026-08-02T10:00:00Z",
    },
    {
      uuid: "33333333-3333-4333-8333-333333333333",
      name: "Aventus",
      slug: "aventus",
      sku: "CR-AV-100",
      price: "12000000.00",
      discount_price: null,
      final_price: "12000000.00",
      stock: 0,
      concentration: "eau_de_parfum",
      target_audience: "men",
      fragrance_family: "woody",
      introduction_year: 2010,
      suitable_season: "all_seasons",
      suitable_usage_time: "day_and_night",
      volume_ml: 100,
      category: { uuid: "dddddddd-dddd-4ddd-8ddd-dddddddddddd", name: "Perfume", slug: "perfume" },
      brand: {
        uuid: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
        name: "Creed",
        slug: "creed",
        country: "france",
      },
      primary_image: null,
      is_featured: false,
      created_at: "2026-08-03T10:00:00Z",
    },
  ],
};

export const productDetail = {
  ...productsPage.results[0],
  description: "An intense trail of spices, lavender, and polished woods.",
  country_of_origin: "france",
  barcode: "3348901567572",
  top_notes: [
    { uuid: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1", name: "Grapefruit", slug: "grapefruit" },
    { uuid: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee2", name: "Cinnamon", slug: "cinnamon" },
  ],
  middle_notes: [{ uuid: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee3", name: "Lavender", slug: "lavender" }],
  base_notes: [{ uuid: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee4", name: "Sandalwood", slug: "sandalwood" }],
  is_active: true,
  images: [
    {
      id: 2,
      image: "http://localhost:8000/media/products/sauvage-side.jpg",
      thumbnail: "http://localhost:8000/media/products/sauvage-side-thumb.jpg",
      is_primary: false,
      display_order: 1,
    },
    productsPage.results[0].primary_image,
  ],
  updated_at: "2026-08-03T10:00:00Z",
};

export const cartResponse = {
  items: [
    {
      product: {
        uuid: productsPage.results[0].uuid,
        slug: productsPage.results[0].slug,
        name: productsPage.results[0].name,
        primary_image: productsPage.results[0].primary_image,
      },
      quantity: 2,
      unit_price: "6250000.00",
      line_total: "12500000.00",
      available_stock: 8,
      available: true,
    },
  ],
  total_quantity: 2,
  total_price: "12500000.00",
  has_unavailable_items: false,
};
