# Generated by Django 6.0.6 on 2026-08-29 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('CUSTOMER_ORDER_CONFIRMED', 'Customer order confirmed'), ('OWNER_ORDER_PROCESSING', 'Owner order processing'), ('CUSTOMER_ORDER_SHIPPED', 'Customer order shipped')], max_length=32)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Owner')], max_length=8)),
                ('recipient_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual review')], default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('operation_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('audit_scrubbed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_deliveries', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='notifications_status_created_idx'), models.Index(condition=models.Q(('status__in', ('PENDING', 'SENDING'))), fields=['next_retry_at', 'id'], name='notifications_due_idx'), models.Index(condition=models.Q(('recipient_phone__isnull', False), ('status__in', ('SENT', 'FAILED'))), fields=['created_at', 'id'], name='notifications_scrub_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'event_type'), name='notifications_order_event_unique'), models.UniqueConstraint(condition=models.Q(('provider_message_id__isnull', False)), fields=('provider', 'provider_message_id'), name='notifications_provider_message_unique'), models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'CUSTOMER_ORDER_CONFIRMED'), ('recipient_type', 'CUSTOMER')), models.Q(('event_type', 'OWNER_ORDER_PROCESSING'), ('recipient_type', 'OWNER')), models.Q(('event_type', 'CUSTOMER_ORDER_SHIPPED'), ('recipient_type', 'CUSTOMER')), _connector='OR'), name='notifications_event_recipient_match'), models.CheckConstraint(condition=models.Q(('recipient_phone__isnull', True), ('recipient_phone__regex', '^09[0-9]{9}$'), _connector='OR'), name='notifications_valid_recipient_phone'), models.CheckConstraint(condition=models.Q(('provider_message_id__isnull', True), ('provider_message_id__gt', ''), _connector='OR'), name='notifications_nonblank_provider_message_id'), models.CheckConstraint(condition=models.Q(('failure_code__regex', '^[A-Za-z0-9_-]*$')), name='notifications_safe_failure_code'), models.CheckConstraint(condition=models.Q(models.Q(('operation_started_at__isnull', True), ('operation_token__isnull', True)), models.Q(('operation_started_at__isnull', False), ('operation_token__isnull', False)), _connector='OR'), name='notifications_operation_lease_paired'), models.CheckConstraint(condition=models.Q(models.Q(('failed_at__isnull', True), ('manual_review_at__isnull', True), ('next_retry_at__isnull', False), ('operation_started_at__isnull', True), ('operation_token__isnull', True), ('sent_at__isnull', True), ('status', 'PENDING')), models.Q(('attempt_count__gt', 0), ('failed_at__isnull', True), ('last_attempt_at__isnull', False), ('manual_review_at__isnull', True), ('next_retry_at__isnull', False), ('operation_started_at__isnull', False), ('operation_token__isnull', False), ('sent_at__isnull', True), ('status', 'SENDING')), models.Q(('failed_at__isnull', True), ('manual_review_at__isnull', True), ('next_retry_at__isnull', True), ('operation_started_at__isnull', True), ('operation_token__isnull', True), ('provider_message_id__gt', ''), ('sent_at__isnull', False), ('status', 'SENT')), models.Q(('failed_at__isnull', False), ('failure_code__gt', ''), ('manual_review_at__isnull', True), ('next_retry_at__isnull', True), ('operation_started_at__isnull', True), ('operation_token__isnull', True), ('sent_at__isnull', True), ('status', 'FAILED')), models.Q(('failed_at__isnull', True), ('failure_code__gt', ''), ('manual_review_at__isnull', False), ('next_retry_at__isnull', True), ('operation_started_at__isnull', True), ('operation_token__isnull', True), ('sent_at__isnull', True), ('status', 'MANUAL_REVIEW')), _connector='OR'), name='notifications_status_lifecycle_consistent'), models.CheckConstraint(condition=models.Q(('status__in', ('SENT', 'FAILED')), ('recipient_phone__regex', '^09[0-9]{9}$'), _connector='OR'), name='notifications_actionable_phone_required'), models.CheckConstraint(condition=models.Q(('audit_scrubbed_at__isnull', True), models.Q(('recipient_phone__isnull', True), ('status__in', ('SENT', 'FAILED'))), _connector='OR'), name='notifications_scrubbed_is_terminal')],
            },
        ),
    ]
