# Generated by Django 6.0.6 on 2026-08-29 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='smsdelivery',
            name='notifications_order_event_unique',
        ),
        migrations.AddField(
            model_name='smsdelivery',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_sms_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='smsdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('recipient_type', 'CUSTOMER')), fields=('order', 'event_type'), name='notifications_customer_order_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='smsdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'OWNER_ORDER_PROCESSING')), fields=('order', 'event_type', 'recipient_user'), name='notifications_owner_order_recipient_unique'),
        ),
        migrations.AddConstraint(
            model_name='smsdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'OWNER_ORDER_PROCESSING'), ('recipient_user__isnull', False)), models.Q(('event_type__in', ('CUSTOMER_ORDER_CONFIRMED', 'CUSTOMER_ORDER_SHIPPED')), ('recipient_user__isnull', True)), _connector='OR'), name='notifications_event_recipient_user_match'),
        ),
    ]
